import { createRouteRegistry } from "@/platform/seo/route-registry";
import type { RouteDefinition } from "@/platform/seo/types";

import { seoConfig } from "./seo.config";

export const routeDefinitions = [
  {
    route: "/",
    class: "public_indexable",
    searchIntent: "plan a short focused work session",
    primaryKeyword: "focus session planner",
    secondaryKeywords: ["focus planner", "work session planner"],
    title: "Focus Session Planner Test Utility",
    description:
      "Plan a fictional focus session with a test-only utility used to validate the reusable starter.",
    h1: "Plan a focused work session",
    pageType: "WebApplication",
    relatedRoutes: ["/seo-starter-checklist", "/pricing", "/privacy", "/terms"],
    lastModified: "2026-08-09",
    reviewStatus: "reviewed",
    reviewFingerprint: "af01d11ecba7e085ab3b397d0cea55cd8e49e24ccaed4ec4440632c9d748db41",
  },
  {
    route: "/seo-starter-checklist",
    class: "public_indexable",
    searchIntent: "review the test utility launch checklist",
    primaryKeyword: "focus planner launch checklist",
    secondaryKeywords: ["test utility checklist"],
    title: "Focus Planner Launch Checklist",
    description: "A test-only launch checklist for the fictional Focus Planner utility.",
    h1: "Focus Planner launch checklist",
    pageType: "Article",
    relatedRoutes: ["/", "/pricing", "/privacy"],
    lastModified: "2026-08-09",
    reviewStatus: "reviewed",
    reviewFingerprint: "1e29748c5d4d07098df44a20418da9c57b6d55c976d068f21b97799bce65af08",
  },
  {
    route: "/pricing",
    class: "public_indexable",
    searchIntent: "review fictional Focus Planner test pricing",
    primaryKeyword: "focus planner pricing",
    secondaryKeywords: ["focus credits"],
    title: "Focus Planner Test Pricing",
    description: "Fictional test-only one-time and monthly credit products for starter validation.",
    h1: "Focus Planner test pricing",
    pageType: "Pricing",
    relatedRoutes: ["/", "/refund-policy", "/terms"],
    lastModified: "2026-08-09",
    reviewStatus: "reviewed",
    reviewFingerprint: "4e1b3f3237be9e7a015541fde86f5a6c5a697018136d6c7a072a87ece109bfe6",
  },
  {
    route: "/privacy",
    class: "public_noindex",
    pageType: "Legal",
    title: "Privacy Notice",
    description: "Test-only privacy notice for the neutral starter product.",
  },
  {
    route: "/terms",
    class: "public_noindex",
    pageType: "Legal",
    title: "Terms of Service",
    description: "Test-only terms of service for the neutral starter product.",
  },
  {
    route: "/acceptable-use",
    class: "public_noindex",
    pageType: "Legal",
    title: "Acceptable Use Policy",
    description: "Test-only acceptable use policy for the neutral starter product.",
  },
  {
    route: "/refund-policy",
    class: "public_noindex",
    pageType: "Legal",
    title: "Refund and Cancellation Policy",
    description: "Test-only refund and cancellation policy for the neutral starter product.",
  },
  {
    route: "/contact",
    class: "public_noindex",
    pageType: "Legal",
    title: "Contact",
    description: "Test-only contact information for the neutral starter product.",
  },
  {
    route: "/account-deletion",
    class: "public_noindex",
    pageType: "Legal",
    title: "Account Deletion",
    description: "Test-only account deletion instructions for the neutral starter product.",
  },
  { route: "/sign-in", class: "public_noindex" },
  { route: "/auth/magic-link/confirm", class: "public_noindex" },
  { route: "/account", class: "private" },
  { route: "/account/security", class: "private" },
  { route: "/account/billing", class: "private" },
  { route: "/account/credits", class: "private" },
  { route: "/account/deleted", class: "private" },
  { route: "/checkout/return", class: "private" },
  { route: "/robots.txt", class: "system" },
  { route: "/sitemap.xml", class: "system" },
  { route: "/api/auth", class: "system" },
  { route: "/api/auth/magic-link/request", class: "system" },
  { route: "/api/auth/magic-link/confirm", class: "system" },
  { route: "/api/account/delete", class: "system" },
  { route: "/api/commerce/checkout", class: "system" },
  { route: "/api/commerce/subscription/cancel", class: "system" },
  { route: "/api/commerce/subscription/resume", class: "system" },
  { route: "/api/commerce/refunds", class: "system" },
  { route: "/api/webhooks/waffo", class: "system" },
  { route: "/api/internal/jobs/account-deletion", class: "system" },
  { route: "/api/internal/jobs/commerce", class: "system" },
  { route: "/api/internal/jobs/credit-expiry", class: "system" },
  { route: "/api/internal/jobs/reconcile", class: "system" },
  { route: "/api/health/live", class: "system" },
  { route: "/api/health/ready", class: "system" },
  { route: "/api/test/emails/latest", class: "system" },
] as const satisfies readonly RouteDefinition[];

export const routeRegistry = createRouteRegistry(seoConfig, routeDefinitions);
