import { createRouteRegistry } from "@/platform/seo/route-registry";
import type { RouteDefinition } from "@/platform/seo/types";

import { seoConfig } from "./seo.config";

export const routeDefinitions = [
  {
    route: "/",
    class: "public_indexable",
    searchIntent: "discover evidence-based game meta boards and tier lists",
    primaryKeyword: "game meta board",
    secondaryKeywords: ["tier list base", "gaming tier list"],
    title: "TierListBase - Evidence-Based Game Meta Boards",
    description:
      "Evidence-based Game Meta Board and tier lists for World of Warcraft: Forever. Multi-source consensus, patch tracking, and transparent tier changes.",
    h1: "Evidence-based game meta boards for players",
    pageType: "WebApplication",
    relatedRoutes: ["/wow-forever/tier-list", "/privacy", "/terms"],
    lastModified: "2026-10-09",
    reviewStatus: "reviewed",
    reviewFingerprint: "f6dc74e630bd9df1edef45671f612084d05590752a335f2d3940d1a87d19acb3",
  },
  {
    route: "/wow-forever/tier-list",
    class: "public_indexable",
    searchIntent: "find current patch tier rankings for World of Warcraft: Forever",
    primaryKeyword: "wow forever tier list",
    secondaryKeywords: ["wow forever meta", "wow forever class tier list"],
    title: "WoW Forever Tier List - Evidence-Backed Meta Rankings",
    description:
      "World of Warcraft: Forever tier list with evidence-based rankings across leveling, dungeons, and PvP. Auditable source consensus and patch change tracking.",
    h1: "WoW Forever Tier List",
    pageType: "WebApplication",
    relatedRoutes: ["/", "/privacy", "/terms"],
    lastModified: "2026-10-09",
    reviewStatus: "reviewed",
    reviewFingerprint: "e12b71187a93f650e55a15873b831240e7f9e38146ba716b51f7d8df0705d22e",
  },
  {
    route: "/privacy",
    class: "public_noindex",
    pageType: "Legal",
    title: "Privacy Notice",
    description: "Project-configured privacy notice.",
  },
  {
    route: "/terms",
    class: "public_noindex",
    pageType: "Legal",
    title: "Terms of Service",
    description: "Project-configured terms of service.",
  },
  {
    route: "/acceptable-use",
    class: "public_noindex",
    pageType: "Legal",
    title: "Acceptable Use Policy",
    description: "Project-configured acceptable use policy.",
  },
  {
    route: "/refund-policy",
    class: "public_noindex",
    pageType: "Legal",
    title: "Refund and Cancellation Policy",
    description: "Project-configured refund and cancellation policy.",
  },
  {
    route: "/contact",
    class: "public_noindex",
    pageType: "Legal",
    title: "Contact",
    description: "Project contact information.",
  },
  {
    route: "/account-deletion",
    class: "public_noindex",
    pageType: "Legal",
    title: "Account Deletion",
    description: "Account deletion instructions and lifecycle summary.",
  },
  { route: "/sign-in", class: "public_noindex" },
  { route: "/auth/magic-link/confirm", class: "public_noindex" },
  { route: "/account", class: "private" },
  { route: "/account/security", class: "private" },
  { route: "/account/billing", class: "private" },
  { route: "/account/credits", class: "private" },
  { route: "/account/deleted", class: "private" },
  { route: "/checkout/return", class: "private" },
  { route: "/robots.txt", class: "system" },
  { route: "/sitemap.xml", class: "system" },
  { route: "/api/auth", class: "system" },
  { route: "/api/auth/magic-link/request", class: "system" },
  { route: "/api/auth/magic-link/confirm", class: "system" },
  { route: "/api/account/delete", class: "system" },
  { route: "/api/commerce/checkout", class: "system" },
  { route: "/api/commerce/subscription/cancel", class: "system" },
  { route: "/api/commerce/subscription/resume", class: "system" },
  { route: "/api/commerce/refunds", class: "system" },
  { route: "/api/webhooks/waffo", class: "system" },
  { route: "/api/internal/jobs/account-deletion", class: "system" },
  { route: "/api/internal/jobs/commerce", class: "system" },
  { route: "/api/internal/jobs/credit-expiry", class: "system" },
  { route: "/api/internal/jobs/reconcile", class: "system" },
  { route: "/api/health/live", class: "system" },
  { route: "/api/health/ready", class: "system" },
  { route: "/api/test/emails/latest", class: "system" },
] as const satisfies readonly RouteDefinition[];

export const routeRegistry = createRouteRegistry(seoConfig, routeDefinitions);
